### ISSUE TITLE
pip not installing the templatetags dir?

### ISSUE THREAD

**Issue by awhillas** [gabrielgrant/django-multiforloop#5]
I did a 

`pip install django-multiforloop`

server restarted but i keep getting the following error:

> 'multifor' is not a valid tag library: Template library multifor not found, tried django.templatetags.multifor,django.contrib.admin.templatetags.multifor,django.contrib.staticfiles.templatetags.multifor,django.contrib.humanize.templatetags.multifor,orders.templatetags.multifor

I looked in the pip folder and templatetags isn't there. I tried 

`pip install git+https://github.com/gabrielgrant/django-multiforloop.git@master`

but no joy ether. Whats up?

**Comment by davidperis92** [comment]
### -Python 2:

Add to pip requirements.py django-multiforloop-patched >= 0.2.0


### -Python 3:

1 ->  Copy multiforloop/templatetags to a templatetags folder in your project.

2 -> replace **from itertools import izip_longest** with **from itertools import zip_longest**
       replace **from django.template.base import Library** with **from django import template**
       replace **register = Library()** with **register = template.Library()**

**Comment by gabrielgrant** [comment]
Thanks @davidperis92 I believe this was fixed a while ago, so going to close
