### ISSUE TITLE
ImportError raised when trying to load 'multiforloop.templatetags.multifor': cannot import name Library

### ISSUE THREAD

**Issue by josedaudi** [gabrielgrant/django-multiforloop#7]
Invalid template library specified. ImportError raised when trying to load 'multiforloop.templatetags.multifor': cannot import name Library

**Comment by gabrielgrant** [comment]
Hey, thanks for the report. Which versions of Django and django-multiforloop are you using?

**Comment by codeprotz** [comment]
i'm using django 1.11 and django-multiforloop 2.0.4

**Comment by codeprotz** [comment]
Finally fixed it @gabrielgrant
