### ISSUE TITLE
TemplateSyntaxError at /

### ISSUE THREAD

**Issue by manikandanb975121** [gabrielgrant/django-multiforloop#8]
could you please help me to solve this error
TemplateSyntaxError at /
'multifor' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_urls
cache
i18n
l10n
log
static
tz

**Comment by gabrielgrant** [comment]
Sorry for the delayed reply. I haven't been using this lib for a while (i'm doing all my templating client-side these days), but happy to review/merge a PR if you track down the issue

**Comment by gabrielgrant** [comment]
I believe this was due to a packaging issue that was fixed a while ago and is now live on PyPI, so going to close. Please feel free to reopen/file a new issue if you're still having trouble!
